version: 2
updates:
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "weekly"
      labels:
          - "dependabot"
          - "github-actions"
    - package-ecosystem: "npm"
      directory: "/src/AzureDevOpsExtension/BicepWhatIfReport"
      schedule:
          interval: "weekly"
      labels:
          - "dependabot"
          - "dependencies"
