name: Auto-Close Done Issues in Project

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  close_done_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: read
    steps:
      - env:
          GH_TOKEN: ${{ secrets.PROJECTS_TOKEN }}
        run: |
          echo "Testing token permissions..."
          gh api https://api.github.com/repos/weekendclimber/BicepWhatIfReport/issues
      
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Close "Done" issues after 1 week in project
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PROJECTS_TOKEN }}
          script: |
            const script = require('${{ github.repository }}/.github/scripts/auto-close-issue.ts')
            await script({github, context, core})
