name: Auto-Close Done Issues in Project

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  close_done_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Close "Done" issues after 1 week in project
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.PROJECTS_TOKEN }}
          script: |
            const script = require('${{ github.workspace }}/.github/workflows/scripts/auto-close-issue.ts')
            await script({github, context, core})
