name: Handle Dependabot PRs

on:
  pull_request:
    types: [opened]
    branches:
      - main  # Change if your default branch is different

permissions:
  contents: read
  pull-requests: write

jobs:
  handle_dependabot_pr:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Add PR to project and set priority
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: ${{ variables.PROJECT_URL }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fields: |
            Priority: High
