name: Handle Dependabot PRs

on:
    pull_request:
        types:
            - opened
        branches:
            - main # Change if your default branch is different

permissions:
    contents: read
    pull-requests: write

jobs:
    handle_dependabot_pr:
        if: github.actor == 'dependabot[bot]'
        runs-on: ubuntu-latest
        steps:
            - name: Add Assignee to Dependabot PR
              uses: actions-ecosystem/action-add-assignees@v1.0.0
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  assignees: ${{ vars.PR_ASSIGNEES }}

            - name: Get Project ID
              id: get_project_id
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  PROJECT_ID=$(curl -X POST \
                    -H "Authorization: Bearer $GITHUB_TOKEN" \
                    -H "Content-Type: application/json" \
                    -H "Accept: application/vnd.github.v3+json" \
                    https://api.github.com/graphql \
                    -d '{
                      "query": "query {
                        repository(owner: \"weekendclimber\", name: \"BicepWhatIfReport\") {
                          projectsV2(first: 10) {
                            nodes {
                              id
                              title
                            }
                          }
                        }
                      }"
                    }' | jq -r '.data.repository.projectsV2.nodes[0].id')
                  echo "Project ID: $PROJECT_ID"
                  echo "project_id=$PROJECT_ID" >> $GITHUB_OUTPUT

            - name: Get Field ID for Priority
              id: get_field_id
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  FIELD_ID=$(curl -X POST \
                    -H "Authorization: Bearer $GITHUB_TOKEN" \
                    -H "Content-Type: application/json" \
                    -H "Accept: application/vnd.github.v3+json" \
                    https://api.github.com/graphql \
                    -d '{
                      "query": "query {
                        node(id: \"${{ steps.get_project_id.outputs.project_id }}\") {
                          ... on ProjectV2 {
                            fields(first: 10) {
                              nodes {
                                id
                                name
                              }
                            }
                          }
                        }
                      }"
                    }' | jq -r '.data.node.fields.nodes[] | select(.name=="Priority") | .id')
                  echo "Field ID: $FIELD_ID"
                  echo "field_id=$FIELD_ID" >> $GITHUB_OUTPUT

            - name: Add Priority Field as High
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  curl -X POST \
                    -H "Authorization: Bearer $GITHUB_TOKEN" \
                    -H "Content-Type: application/json" \
                    -H "Accept: application/vnd.github.v3+json" \
                    https://api.github.com/graphql \
                    -d '{
                      "query": "mutation($input: UpdateProjectNextItemFieldValueInput!) {
                        updateProjectNextItemFieldValue(input: $input) {
                          projectNextItem {
                            id
                          }
                        }
                      }",
                      "variables": {
                        "input": {
                          "projectId": "\"${{ steps.get_project_id.outputs.project_id }}\"",
                          "itemId": "\"${{ github.event.pull_request.node_id}}\"",
                          "fieldId": "\"${{ steps.get_field_id.outputs.field_id }}\"",
                          "body": "Priority: High"
                        }
                      }
                    }'